version: '2.4'
services:
  splash:
    logging:
      driver: json-file
      options:
        max-size: "2m"
    image: scrapinghub/splash
    ports:
      - 8050   # HTTP API
    command: --maxrss 4000
    mem_limit: 4.5G
    networks:
      - xtnet

  splash.web:
    image: nginx:1.22.0
    ports:
      - 80 
    volumes:
      - ./splash.conf:/etc/nginx/conf.d/default.conf
      - ./wait-for-it.sh:/wait-for-it.sh
    command: >
            /bin/sh -c "/wait-for-it.sh -t 0 splash:8050 -- echo 'splash is up';
                        service nginx start; tail -f /dev/null"
    depends_on:
      - splash 
    networks:
      - xtnet


networks:
    xtnet:
        external: true
