version: '2.4'
services:
  splash:
    container_name: splash
    logging:
      driver: json-file
      options:
        max-size: "2m"
    image: scrapinghub/splash
    ports:
      - 8050   # HTTP API

    networks:
      - xtnet

networks:
    xtnet:
        external: true
